Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.84:40294'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.84:54702'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:    tcp://10.148.0.84:42004
distributed.worker - INFO -          Listening to:    tcp://10.148.0.84:42004
distributed.worker - INFO -              nanny at:          10.148.0.84:40294
distributed.worker - INFO -              bokeh at:           10.148.0.84:8789
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.34:40109
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.5370796.datarmor0/worker-2ogqfz31
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.1.34:40109
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:    tcp://10.148.0.84:43191
distributed.worker - INFO -          Listening to:    tcp://10.148.0.84:43191
distributed.worker - INFO -              nanny at:          10.148.0.84:54702
distributed.worker - INFO -              bokeh at:          10.148.0.84:46839
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.34:40109
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.5370796.datarmor0/worker-u665jtk_
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.1.34:40109
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Stopping worker at tcp://10.148.0.84:42004
distributed.worker - INFO - Stopping worker at tcp://10.148.0.84:43191
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.84:54702'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.84:40294'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
