Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.1.1:39581'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.1.1:57356'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:     tcp://10.148.1.1:48527
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:     tcp://10.148.1.1:39409
distributed.worker - INFO -          Listening to:     tcp://10.148.1.1:39409
distributed.worker - INFO -          Listening to:     tcp://10.148.1.1:48527
distributed.worker - INFO -              nanny at:           10.148.1.1:57356
distributed.worker - INFO -              bokeh at:           10.148.1.1:36428
distributed.worker - INFO -              nanny at:           10.148.1.1:39581
distributed.worker - INFO - Waiting to connect to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:            10.148.1.1:8789
distributed.worker - INFO - Waiting to connect to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.1346232.datarmor0/worker-3tw_pl_6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.1346232.datarmor0/worker-bb_elk5v
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 3.57s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/dask/array/chunk.py:228: ComplexWarning: Casting complex values to real discards the imaginary part
  return x.astype(astype_dtype, **kwargs)
distributed.utils_perf - INFO - full garbage collection released 26.23 MB from 129733 reference cycles (threshold: 10.00 MB)
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/dask/array/chunk.py:228: ComplexWarning: Casting complex values to real discards the imaginary part
  return x.astype(astype_dtype, **kwargs)
distributed.worker - INFO - Can't find dependencies for key ('isna-where-df72cf21e168d64356411fd221dff700', 344, 9, 0)
distributed.worker - INFO - Dependent not found: ('open_dataset-3ab3a6dda2e81b072f4fd482d70e43f9Eta-9f33644c6ce269d402addeb341b79b3c', 344, 9, 0) 0 .  Asking scheduler
distributed.utils_perf - INFO - full garbage collection released 46.33 MB from 259433 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 13.43 MB from 64853 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 11.14 MB from 64866 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 21.73 MB from 129822 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 16.04 MB from 130050 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Stopping worker at tcp://10.148.1.1:39409
distributed.worker - INFO - Stopping worker at tcp://10.148.1.1:48527
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.1.1:57356'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.1.1:39581'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
