Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.217:37711'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.217:44358'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.217:45577
distributed.worker - INFO -          Listening to:   tcp://10.148.0.217:45577
distributed.worker - INFO -              nanny at:         10.148.0.217:44358
distributed.worker - INFO -              bokeh at:          10.148.0.217:8789
distributed.worker - INFO - Waiting to connect to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.1346232.datarmor0/worker-34sp5_fy
distributed.worker - INFO - -------------------------------------------------
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.217:45581
distributed.worker - INFO -          Listening to:   tcp://10.148.0.217:45581
distributed.worker - INFO -              nanny at:         10.148.0.217:37711
distributed.worker - INFO -              bokeh at:         10.148.0.217:41536
distributed.worker - INFO - Waiting to connect to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.1346232.datarmor0/worker-2g8pptit
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 3.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 3.26s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 7.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 7.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 22.84s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 25.06s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.utils_perf - INFO - full garbage collection released 149.31 MB from 87 reference cycles (threshold: 10.00 MB)
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/dask/array/chunk.py:228: ComplexWarning: Casting complex values to real discards the imaginary part
  return x.astype(astype_dtype, **kwargs)
distributed.utils_perf - INFO - full garbage collection released 203.10 MB from 65414 reference cycles (threshold: 10.00 MB)
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/dask/array/chunk.py:228: ComplexWarning: Casting complex values to real discards the imaginary part
  return x.astype(astype_dtype, **kwargs)
distributed.utils_perf - INFO - full garbage collection released 52.14 MB from 602 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 49.71 MB from 0 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 10.61 MB from 64850 reference cycles (threshold: 10.00 MB)
distributed.worker - ERROR - Worker stream died during communication: tcp://10.148.0.144:60204
Traceback (most recent call last):
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/comm/core.py", line 186, in connect
    quiet_exceptions=EnvironmentError)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/worker.py", line 1774, in gather_dep
    who=self.address)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/core.py", line 608, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/core.py", line 719, in connect
    connection_args=self.connection_args)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/comm/core.py", line 195, in connect
    _raise(error)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/comm/core.py", line 178, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.148.0.144:60204' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x2aab33f96f98>: ConnectionRefusedError: [Errno 111] Connection refused
distributed.utils_perf - INFO - full garbage collection released 24.79 MB from 129706 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 42.71 MB from 259403 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 23.88 MB from 194554 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 84.85 MB from 64 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 10.89 MB from 64853 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 965.99 MB from 4742206 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Stopping worker at tcp://10.148.0.217:45577
distributed.worker - INFO - Stopping worker at tcp://10.148.0.217:45581
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.217:37711'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.217:44358'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
