Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.212:46315'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.212:36283'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.212:46272
distributed.worker - INFO -          Listening to:   tcp://10.148.0.212:46272
distributed.worker - INFO -              nanny at:         10.148.0.212:36283
distributed.worker - INFO -              bokeh at:          10.148.0.212:8789
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.2935111.datarmor0/worker-qg0cz2dn
distributed.worker - INFO - -------------------------------------------------
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.212:54492
distributed.worker - INFO -          Listening to:   tcp://10.148.0.212:54492
distributed.worker - INFO -              nanny at:         10.148.0.212:46315
distributed.worker - INFO -              bokeh at:         10.148.0.212:37009
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.2935111.datarmor0/worker-sl8pelhs
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.utils_perf - INFO - full garbage collection released 223.88 MB from 233 reference cycles (threshold: 10.00 MB)
distributed.worker - WARNING -  Compute Failed
Function:  getter
args:      (ImplicitToExplicitIndexingAdapter(array=LazilyOuterIndexedArray(array=NativeEndiannessArray(array=LazilyOuterIndexedArray(array=<xarray.backends.zarr.ZarrArrayWrapper object at 0x2aab37f9d4e0>, key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None))))), key=BasicIndexer((slice(None, None, None), slice(None, None, None), slice(None, None, None))))), (slice(167, 168, None), slice(0, 4320, None), slice(0, 4320, None)))
kwargs:    {}
Exception: RuntimeError('error during blosc decompression: -1',)

distributed.worker - INFO - Stopping worker at tcp://10.148.0.212:46272
distributed.worker - INFO - Stopping worker at tcp://10.148.0.212:54492
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.212:46315'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.212:36283'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
