Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.64:40535'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.64:56713'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:    tcp://10.148.0.64:56943
distributed.worker - INFO -          Listening to:    tcp://10.148.0.64:56943
distributed.worker - INFO -              nanny at:          10.148.0.64:56713
distributed.worker - INFO -              bokeh at:           10.148.0.64:8789
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:    tcp://10.148.0.64:52512
distributed.worker - INFO -          Listening to:    tcp://10.148.0.64:52512
distributed.worker - INFO -              nanny at:          10.148.0.64:40535
distributed.worker - INFO -              bokeh at:          10.148.0.64:40218
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.2935111.datarmor0/worker-1o5nu9np
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.2935111.datarmor0/worker-5kyecvan
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Stopping worker at tcp://10.148.0.64:56943
distributed.worker - INFO - Stopping worker at tcp://10.148.0.64:52512
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.64:56713'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.64:40535'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
