Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/distributed/utils.py:137: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.1.107:57116'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.1.107:38529'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/distributed/utils.py:137: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://10.148.1.107:37814
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/distributed/utils.py:137: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://10.148.1.107:47158
distributed.worker - INFO -          Listening to:   tcp://10.148.1.107:37814
distributed.worker - INFO -          Listening to:   tcp://10.148.1.107:47158
distributed.worker - INFO -          dashboard at:         10.148.1.107:45288
distributed.worker - INFO -          dashboard at:         10.148.1.107:35820
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.93:49313
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.93:49313
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         14
distributed.worker - INFO -               Threads:                         14
distributed.worker - INFO -                Memory:                   60.00 GB
distributed.worker - INFO -                Memory:                   60.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.8339750.datarmor0/worker-_05e9mkt
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.8339750.datarmor0/worker-0pgy0mgz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.1.93:49313
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://10.148.1.93:49313
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.1.107:57116'
Terminated
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.1.107:38529'
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 416, in <module>
    go()
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 412, in go
    main()
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 403, in main
    raise TimeoutError("Timed out starting worker.") from None
tornado.util.TimeoutError: Timed out starting worker.
